//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employee_API.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE @id = [dbo].[CreateEmployees] @firstName, @lastName, @dateOfBirth, @designation, @dateOfJoining, @CTC.
        /// </summary>
        public static string CreateEmployeeCommand {
            get {
                return ResourceManager.GetString("CreateEmployeeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[CreateEmployees] 
        ///	@firstName as varchar(200),
        ///	@lastName as varchar(200),
        ///	@dateOfBirth as date,
        ///	@designation as varchar(200),
        ///	@dateOfJoining as date,
        ///	@CTC as int
        ///AS
        ///BEGIN
        ///   INSERT INTO EMPLOYEES(
        ///		firstName,
        ///		lastName,
        ///		dateOfBirth,
        ///		designation,
        ///		dateOfJoining,
        ///		ctc)
        ///	VALUES
        ///	(
        ///		@firstName,
        ///		@lastName,
        ///		@dateOfBirth,
        ///		@designation,
        ///		@dateOfJoining,
        ///		@CTC
        ///	)
        ///	return SCOPE_IDENTITY()
        ///END.
        /// </summary>
        public static string CreateEmployees_Proc {
            get {
                return ResourceManager.GetString("CreateEmployees_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[DeleteEmployees] @id.
        /// </summary>
        public static string DeleteEmployeeCommand {
            get {
                return ResourceManager.GetString("DeleteEmployeeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[DeleteEmployees] 
        ///	@Id as int
        ///AS
        ///BEGIN
        ///	DELETE FROM EMPLOYEES WHERE Id = @Id
        ///END.
        /// </summary>
        public static string DeleteEmployees_Proc {
            get {
                return ResourceManager.GetString("DeleteEmployees_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[GetEmployees] 
        ///	@Id as int
        ///AS
        ///BEGIN
        ///	SELECT * FROM EMPLOYEES WHERE (@Id = -1 OR Id = @Id)
        ///END.
        /// </summary>
        public static string GetEmployees_Proc {
            get {
                return ResourceManager.GetString("GetEmployees_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[GetEmployees] @id.
        /// </summary>
        public static string GetEmployeesQuery {
            get {
                return ResourceManager.GetString("GetEmployeesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE [dbo].[UpdateEmployees] @id, @firstName, @lastName, @dateOfBirth, @designation, @dateOfJoining, @CTC.
        /// </summary>
        public static string UpdateEmployeeCommand {
            get {
                return ResourceManager.GetString("UpdateEmployeeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER PROCEDURE [dbo].[UpdateEmployees] 
        ///	@Id as int,
        ///	@firstName as varchar(200),
        ///	@lastName as varchar(200),
        ///	@dateOfBirth as date,
        ///	@designation as varchar(200),
        ///	@dateOfJoining as date,
        ///	@CTC as int
        ///AS
        ///BEGIN
        ///	UPDATE EMPLOYEES SET
        ///		firstName = @firstName,
        ///		lastName = @lastName,
        ///		dateOfBirth = @dateOfBirth,
        ///		designation = @designation,
        ///		dateOfJoining = @dateOfJoining,
        ///		ctc = @CTC
        ///	WHERE
        ///		Id = @Id
        ///END.
        /// </summary>
        public static string UpdateEmployees_Proc {
            get {
                return ResourceManager.GetString("UpdateEmployees_Proc", resourceCulture);
            }
        }
    }
}
